### PR TITLE
WIP  Create toggle button for oscilloscope

### PR DESCRIPTION
**Pull request by michiboo**
This PR is mainly for UI improvement for oscilloscope

### CODE REVIEW

**Comment by fundamental** [comment]
Looks like I forgot to mention the fix to prevent the flicker in the oscilloscope:

```
diff --git a/example/ZynOscilloscope.qml b/example/ZynOscilloscope.qml
index cf7caa3..aa477a4 100644
--- a/example/ZynOscilloscope.qml
+++ b/example/ZynOscilloscope.qml
@@ -72,8 +72,8 @@ Widget {
             run_view.valueRef.watch run_view.extern
             now     = Time.new
             @last ||= now
-            default = [10] * 200
-            update_points(default) if((now-@last)>0.1)
+            #default = [10] * 200
+            #update_points(default) if((now-@last)>0.1)
         }
 
         function draw(vg){
```

That should resolve that problem.
The oscilloscope button seems to work as intended for Add Synth. For Sub Synth it moves the UI into a broken state with the most recent commit. For Pad Synth it looks like it works, but I was testing the UI commit on it's own with the current master for the zynaddsubfx engine which looks like it is missing a few of the newer watchpoints you have in Pad synth.

Additionally I noticed some waveform desync in add synth, though there's a chance that was due to an older version of the zynaddsubfx core. Is that something you're noticing with current commits?

**Comment by michiboo** [comment]
Hi, For Sub Synth from my side i didn't see any broken state......
For Pad synth the new watch point should be here with this branch.
I fixed the waveform desync issue in add synth, it was a small bug.

**Comment by fundamental** [comment]
Before clicking oscilloscope:
2019-08-sub-before

After clicking oscilloscope:
2019-09-sub-after

See that the bottom fields have changed and they have shifted vertically.

**Comment by fundamental** [comment]
Things seem closer in the sub synth view, however they're still not quite right.

In ZynSubSynth.qml I would expect the change to be the 'vis' view to 'oscilloscope' similar to the approach in ZynAddSynth. Per the change in ZynAddSynth, I do see a set_view_pos to 'global', though I'd expect it should be fine for the user if they end up in the global subview or the voice subview. Taking the ZynSubSynth.qml consider having the oscilloscope visualization appearing when using the ZynSubAmp.qml's subview. Right now that subview doesn't support swappable visualizations. That functionality could be added there (and similarly in other subviews) by changing the directly instantiated ZynEnvEdit {} widget with a Swappable {} widget. Then using the set_view() methods in other locations like ZynSubSynth.qml or ZynAddSynth.qml as reference you can extend the currently less flexible sub synth subviews.


Additionally there needs to be some handling of invalid UI states when transitioning around.
1. click sub
2. click amplitude
3. click oscilloscope
4. click pad (or alternatively click add)

After 4 you're left with a full size oscilloscope visualization instead of the (AFAIK) expected embedded oscilloscope view. You can see in ZynAddSynth.qml::set_view() there's a check if a subview is valid. A similar thing can be done with other view types, but essentially the goal is to constrain valid views when transitioning from elsewhere in the UI.


Outside of these issues it's mostly getting down to documenting where some of the stuff under the hood is coming from. I could see things going towards some more advanced triggering, but that would be out-of-scope for the near term.

**Pull request merged**
